### ISSUE TITLE
How to make it so that swagger ui works both on localhost AND on heroku?

### ISSUE THREAD

**Issue by bennettl** [richhollis/swagger-docs#100]
i want to be able to run swagger ui on both my localhost:3000 and on my production site in heroku. I tried setting the base path differently in my swagger configuration as follows:

Swagger::Docs::Config.register_apis({
  "1.0" => {
    api_file_path: "public/",
    base_path: Rails.application.config.base_path,
    clean_directory: false
  }
})

And setting the appropriate urls in #production.rb and #development.rb configuration files. I push the changes to heroku, ran "heroku run rake swagger:docs", but

**Comment by bennettl** [comment]
@derrek I've followed the steps as you suggested

1) Fork the build back repo
2) Change the code for swagger docs: https://github.com/bennettl/heroku-buildpack-ruby
3) Set the build back url
4) Push a change to heroku so the swagger docs would run

I see the swagger docs generate on console

remote: -----> Generating Swagger documentation
remote:        Running: rake swagger:docs
remote:        1.0: 3 processed / 0 skipped
remote:        Swagger documentation generation completed (4.66s)

But there's nothing here: http://find-the-sand.herokuapp.com/swagger/swagger-ui

**Comment by derrek** [comment]
Swagger is responding at that url.  Something is incorrect in your setup such that the swagger app can't see the generated files.  I switched your url to https://find-the-sand.herokuapp.com/swagger/swagger-ui and the swagger app revealed: fetching resource list: http://localhost:3000/api-docs.json - so it's still trying to look at localhost:3000.  I believe you have to fiddle with your configuration a bit more.

**Comment by bennettl** [comment]
You're right! I modified the index.html of the swagger -ui to point to "http://find-the-sand.herokuapp.com/api-docs.json" instead of the localhost, but not I'm seeing the error message "SwaggerOperation Beaches_index is missing path." on the swagger ui. I recall seeing this issue before, not sure exactly what's wrong. It seems to be working fine on my localhost (when I point to localhost:3000)...

**Comment by clevertension** [comment]
the latest solution is 
 heroku buildpacks:set https://github.com/heroku/heroku-buildpack-erlang

see [this](https://devcenter.heroku.com/articles/buildpacks)

**Comment by msv300** [comment]
i forked this build pack and made the given changes then i ran `rake gem:install[bundler,1.13.6]`. but the rake is not running i'm getting this error 

rake aborted!
Command failed with status (22): [/home/ubuntu/workspace/heroku-buildpack-ru...]
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'

Can anybody help me out.. Thanks in advance.
