### ISSUE TITLE
Singular resources are not treated correctly

### ISSUE THREAD

**Issue by rusterholz** [richhollis/swagger-docs#103]
Rails supports the concept of a [Singular Resource](http://guides.rubyonrails.org/routing.html#singular-resources), but `rake swagger:docs` does not correctly treat such resources as singular when generating docs.

**Example:** In our `routes.rb` file we declare the following routes:

    resource :garage, only: [:show, :create] do
      put    ':vehicle_id'            => 'garages#update',        on: :collection, as: 'vehicle'
      delete ':vehicle_id'            => 'garages#destroy',       on: :collection
    end

And in the `GaragesController` we have the following swagger declaration:

    swagger_controller :garage, 'Garage Management'

**Result:** An API file is created entitled `garages.json` which contains the line `"resourcePath": "garages",` and the `api-docs.json` file has an entry added with the line `"path": "garages.{format}"`.

**Expected:** The created API file should be entitled `garage.json` and contain the line `"resourcePath": "garage",` and the entry added to the  `api-docs.json` file should have the line `"path": "garage.{format}"`.

I should note that the actual URLs which Swagger puts in the API file are correct, e.g. they match the singular resource routes that Rails generated. So the functionality of the files is not impacted; still, they should be shown correctly.

**Comment by richhollis** [comment]
We don't have any support for that but can consider a PR if you want to look at this. Thanks!
