### ISSUE TITLE
swagger-docs not picking up nickname

### ISSUE THREAD

**Issue by josephmisiti** [richhollis/swagger-docs#106]
I want to override nickname. The issue I am seeing is that if your gem generates the nickname, the swagger-codegen software creates invalid Python (and possibly more also) because it uses this code.
Here is an example

```python
class ArticlesApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def Api::V2::Articles#index(self, **kwargs):
        """Read a list of articles

        Args:
```

That is not valid Python obviously.

**Comment by richhollis** [comment]
Closing as this appears to be for a python library.
