### ISSUE TITLE
Swagger v2

### ISSUE THREAD

**Issue by x3mka** [richhollis/swagger-docs#107]
Any plans supporting Swagger v2?

**Comment by jlehman** [comment]
I second this as well. Swagger 2.0 has been out for quite a while now and I'd be glad to assist in the transition, but not sure if its on the plan.

**Comment by fotinakis** [comment]
Just to steal some thunder and offer an alternative here, Swagger 2.0 is now supported by the [swagger-blocks](https://github.com/fotinakis/swagger-blocks/) gem if you're interested (bearing in mind that it's an unrelated project and a different doc format).

**Comment by okolehao** [comment]
@jlehman  not sure if @richhollis  has time anymore to maintain and port to Swagger 2.0 (haven't seen any recent updates on the project), if not perhaps @fotinakis  or someone has a tool to migrate from swagger-docs to swagger-blocks format.

**Comment by bf4** [comment]
we're stuck on this version too.. I'm considering forking swagger-docs to output valid swagger docs an use swagger-tools to convert to swagger 2.0

**Comment by okolehao** [comment]
we didn't have enough time, so we just manually re-coded everything from swagger-docs to swagger-blocks - thanks @fotinakis / it would be cool if there was an easier upgrade

**Comment by fotinakis** [comment]
You're welcome @okolehao! :) Glad it's useful.

**Comment by x3mka** [comment]
@bf4 we end up not moving to 2.0 now, but you can try swagger-tools without forking by just adjusting sawgger:docs rake task like this:

```ruby
namespace :swagger do
  task :convert_to_20 do
    # use tools or custom code to convert
  end

  task :docs do
    Rake::Task['swagger:docs'].invoke
    Rake::Task['swagger:convert_to_20'].invoke
  end

end
```

**Comment by bf4** [comment]
@x3mka so, what you're say is that I could write a transform.  Yeah, maybe.  I run `bin/swagger` that I derived from the rake task to get better output.

```ruby
#!/usr/bin/env ruby
require File.expand_path("../../config/environment", __FILE__)
# https://github.com/richhollis/swagger-docs/blob/master/lib/tasks/swagger.rake
ENV["SD_LOG_LEVEL"] = "1"
results = Swagger::Docs::Generator.write_docs(Swagger::Docs::Config.registered_apis)
results.each do |k, v|
  puts "Api Version: #{k}: "
  print "#{v[:processed].count} processed "
  ok_skip_reasons = %i[not_swagger_resource empty_path]
  skipped = v[:skipped].reject { |s| ok_skip_reasons.include?(s[:reason]) }
  print "#{skipped.count} skipped, #{skipped.map { |s| s.values_at(:reason, :path) }}"
  print "\n"
end
```

**Comment by x3mka** [comment]
@bf4 Agreed, but nothing prevents you from changing output json content before using conversion tools.

**Comment by davidkovsky** [comment]
Would the maintainers consider a PR on the README? I see there's already a mention of swagger-blocks but there's nothing to deter someone from spending time on swagger-docs before realizing they'll either need to rely on the converter rake task or switch in order to get v2 support.

**Comment by jdonboch** [comment]
+1

**Comment by richhollis** [comment]
Have added a note at the top of the README regarding support.
