### ISSUE TITLE
How to do integration tests

### ISSUE THREAD

**Issue by ceritium** [richhollis/swagger-docs#109]
Hi, I am using swagger-docs to generate my swagger spec and [https://github.com/d4be4st/swagger-ui_rails](https://github.com/d4be4st/swagger-ui_rails) for the UI.

I needed integration tests of some features, but I had problems because the URIs are different in each environment.

I solved in this way:
```ruby
class Swagger::Docs::Config
  def self.transform_path(path, api_version)
    "#{Rails.application.config.host}/docs/#{path}"
  end
end

Swagger::Docs::Config.register_apis({
  "1.0" => {
    :api_extension_type => :json,
    :base_path => Rails.application.config.host,
...
```

And before each test I run the next code:
```ruby

visit(root_path)
uri = URI(current_url)
base_path = "http://#{uri.host}:#{uri.port}"
prev_host = Rails.application.config.host

Rails.application.config.stubs(:host).returns(base_path)
Swagger::Docs::Config.registered_apis["1.0"][:base_path] = base_path
Rake::Task["swagger:docs"].invoke

```

Of course the swagger docs are ignored and its auto generated during the deploy.
Someone has any suggestion? Some idea to make it easy? Is useful my snippet for someone?
Thanks.

**Comment by richhollis** [comment]
Closing (beyond scope of gem)
