### ISSUE TITLE
Multiple routes for 1 method

### ISSUE THREAD

**Issue by developer88** [richhollis/swagger-docs#111]
Lets say i have several api routes for 1 method like:

    def index
        ...
    end

    get 'cities(/by/country/:country_id), to: 'cities#index'

or

    get 'cities', to: 'cities#index'
    get 'cities/by/country/:country_id', to: 'cities#index'

Is it possible to show all routes in Swagger API docs? or docs for each route?

For now i using alias:

    alias :index_by_country :index

then change route:

    get 'cities/by/country/:country_id', to: 'cities#index_by_country'

then describe this method as usual. But i think this is not a proper way.

**Comment by doliveirakn** [comment]
+1

**Comment by richhollis** [comment]
We don't have any support for that but can consider a PR if you want to look at this. Thanks!
