### ISSUE TITLE
response with array of models?

### ISSUE THREAD

**Issue by dgobaud** [richhollis/swagger-docs#112]
Trying to specify a response that returns an array of models such as:

response :ok, 'Success', :array => :Vehicle

don't see how to do this and the method signature of response:

def response(status, text = nil, model = nil)

doesn't seem to support it. Is there a way to do this?

Thanks!

**Comment by floatbox** [comment]
Yes, I need it, too

**Comment by wintondeshong** [comment]
+1

**Comment by jstoup111** [comment]
What does your structure look like?

```
swagger_model :Users
  property :users, :array, :required, 'List of user Objects', items: { '$ref' => :User }
end
```

Gives me this

```
"users": {
          "type": "array",
          "description": "List of user Objects",
          "items": {
            "$ref": "User"
          }
        }
```

**Comment by dgobaud** [comment]
for properties something like below has worked but this doesnt work for response

property :refunds, :array, :required, 'Refunds', {:items => {:type => :Refund}}

**Comment by jstoup111** [comment]
You have to have a structure like the one I gave.  ```items: { type: :Refund}``` does not work.  ```items: { '$ref' => :Refund```  Will work.

**Comment by dgobaud** [comment]
doesn't seem to work

swagger_api :index do
    summary 'Returns the fuel types'
    
    response :ok, 'Success', items: { '$ref' => :FuelType }
    response :unauthorized
  end

generates

  {
      "path": "api/v1/fuel_types.json",
      "operations": [
        {
          "summary": "Returns the fuel types",
          "responseMessages": [
            {
              "code": 200,
              "responseModel": {
                "items": {
                  "$ref": "FuelType"
                }
              },
              "message": "Success"
            },
            {
              "code": 401,
              "responseModel": null,
              "message": "Unauthorized"
            }
          ],
          "method": "get",
          "nickname": "Api::V1::FuelTypes#index"
        }
      ]
    }

which in the UI doesn't render anything under response model

**Comment by jstoup111** [comment]
The response only takes a code, message and model

```
swagger_model :User do
  property :id, :integer, :required, 'Id of the user'
  property :email, :string, :required, 'email of the user'
end

swagger_model :Users do
  property :users, :array, :required, 'List of user Objects', items: { '$ref' => :User }
end

swagger_api :index do
  summary 'Returns the users'
  response :ok, nil, :Users
  response :unauthorized
end
```

The Users (array) model references the User model (single).  This means your response for Index be wrapped in an object.  This is good because if you're paging you can add your paging properties and it keeps your object clean.  The structure would look something like this:

```
{
  users: [
    {
      id: 1,
      email: 'test@test.com'
    },
    {
      id: 2,
      email: 'test2@test.com'
    }
  ]
}
```

**Comment by dgobaud** [comment]
Interesting - seems odd though to have to make a wrapper object for each model...

**Comment by richhollis** [comment]
Thanks @jstoup111. Closing.
