### ISSUE TITLE
Support for default param values?

### ISSUE THREAD

**Issue by kamoh** [richhollis/swagger-docs#114]
Is there any support for default values for parameters? It looks like Swagger supports this with the defaultValue key but there isn't gem support. If it isn't supported or if there are no plans to add this, I work on adding this later.

**Comment by philipgiuliani** [comment]
[In the following line](https://github.com/richhollis/swagger-docs/blob/master/lib/swagger/docs/dsl.rb#L44) you can see that you can pass a hash as last parameter. I looked a bit how the serialization works an the gem is camelizing all attributes of this hash.

```ruby
param :query, :platform, :string, :optional, "Platform (android|ios)", default_value: "android"
````

This code snipped worked for me! Be sure to pass it as 6th argument.

**Comment by richhollis** [comment]
Thanks @philipgiuliani sharing the example.

Closing.
