### ISSUE TITLE
base_api_controller/base_api_controllers config not work

### ISSUE THREAD

**Issue by anonymelon** [richhollis/swagger-docs#115]
I have a requirement to specify a subclass of `ActionController::Base` eg `MyAPIController`, so I add a config `base_api_controller: MyAPIController`, but it not work. I have read the source code, just replace the `base_api_controller` method's default value to `MyAPIController`, it works as expected.

I'm wondering how to use this config, can anyone give me a example?

And I find a hidden config `controller_base_path`, I use it to specify the controller path which I want to generate docs, it works, but this solution seems not official :(

**Comment by wintondeshong** [comment]
+1 I am also experiencing this issue. I was able to just delete the base_api_controller/s config line and it started working again.

**Comment by CQBinh** [comment]
From [docs](https://github.com/richhollis/swagger-docs#inheriting-from-a-custom-api-controller), you can config like this:
```
class Swagger::Docs::Config
  def self.base_api_controller
    ActionController::API  
  end
end

Swagger::Docs::Config.register_apis({
  "1.0" => {
    :controller_base_path => "",
    :api_file_path => "public"
  }
})
```
And then test by printing to console:
```
p Swagger::Docs::Config.base_api_controller
```
Or you can see on issue #75 
```
Swagger::Docs::Config.base_api_controller = ActionController::API 
```
Then run `rake swagger:docs` to see what happen.

**Comment by richhollis** [comment]
Closing - please re-open if still an issue.
