### ISSUE TITLE
Swagger UI v. 2.1.1-M2 Support?

### ISSUE THREAD

**Issue by JulienDefrance** [richhollis/swagger-docs#116]
Hello,

Perhaps an already known issue.
I am using Swagger Docs gem as part of my RoR application, and so far had one instance running Swagger UI v. 2.0.24

This version was fine, however, had problems supporting nested attributes or more precisely, the swagger_docs swagger_model concept, once rendering the pages. Not able to edit the attributes inline, losing all the value of using Swagger Docs, and having other developers of our team using HttpRequester or whatever Rest Client of their choice to actually test/submit requests.

I was somehow expecting this to be fixed in 2.1.1 (or under the asumption it would, based on my readings)
However when giving a try to 2.1.1-M2 recently, it appeared a whole new set of problems started to appear, starting from being unable to load/render our swagger_docs generated JSON files in that new UI.

A sample would be:
http://petstore.swagger.io/?url=http://data-api.smartzip-services.com/api/1.0/api-docs.json

Is there anyone actively working on that project and planning on such support?
Does the JSON have a different format now?
Are their any known workaround? Extra step to convert it to a valid JSON file that V2.2.1 can interpret?

Would be glad to help if need be!

**Comment by JulienDefrance** [comment]
Any update on version 2.0 support?

**Comment by fotinakis** [comment]
Known issue, swagger-docs doesn't support v2 (see https://github.com/richhollis/swagger-docs/issues/107).

If you're interested in a different project, I'm the maintainer of [swagger-blocks](https://github.com/fotinakis/swagger-blocks) which does have full support for Swagger v2.

**Comment by richhollis** [comment]
Closing as not currently supported
