### ISSUE TITLE
RequestUrl missing slash

### ISSUE THREAD

**Issue by Diobox** [richhollis/swagger-docs#117]
There's a slash missing after the base url in the request url on swagger ui.
The path in the outputted JSON is wrong. Also all the slashes are being escaped in the JSON output. Is that normal?
I'm ending up with this. 

`http://localhost:3000api/v2/account/billing`

**Comment by Diobox** [comment]
Here's my config
```
class Swagger::Docs::Config
    def self.transform_path(path, api_version)
      # Make a distinction between the APIs and API documentation paths.
      "/apidocs/#{path}"
    end
  end

  Swagger::Docs::Config.register_apis({
    '1.0' => {
      controller_base_path: '',
      api_file_path: 'public/apidocs',
      base_path: 'http://localhost:3000',
      #base_api_controller: "ApiController",
      clean_directory: true,
      camelize_model_properties: false
    }
  })
```

**Comment by pranavpr** [comment]
Faced the same issue. Created a pull request fixing the same.

**Comment by perldork** [comment]
For those of you who don't want to use a forked repo and wait for the path @pranavpr did to be integrated you can put this monkey patch in ```config/initializers/swagger_docs.rb``` (or whatever your initializer is called to fix it as an interim solution.

```
class Swagger::Docs::Generator
  def self.trim_slashes(str)
    "/" + trim_leading_slash(trim_trailing_slash(str))
  end
end
```

**Comment by jdkealy** [comment]
Thanks perldork!! totally worked, so helpful!!

**Comment by Bailei** [comment]
Thanks @perldork, it works perfectly!

**Comment by wakandan** [comment]
+1. I was pulling my hairs out with this bug too!

**Comment by xuyao91** [comment]
+1,I have the error too,and I used perldork's code,but api-docs.json's path don't change
api-docs.json
```
{
apiVersion: "1.0",
swaggerVersion: "1.2",
basePath: "http://localhost:3004/",
apis: [
{
path: "users.{format}",
description: "Users"
}
],
info: {
title: "Swagger Sample App",
description: "This is a sample description.",
termsOfServiceUrl: "http://helloreverb.com/terms/",
contact: "apiteam@wordnik.com",
license: "Apache 2.0",
licenseUrl: "http://www.apache.org/licenses/LICENSE-2.0.html"
}
}
```

users.json
```
{
apiVersion: "1.0",
swaggerVersion: "1.2",
basePath: "http://localhost:3004/",
resourcePath: "users",
apis: [
{
path: "/users",
operations: [
{
summary: "Fetches all users",
responseMessages: [
{
code: 401,
responseModel: null,
message: "Unauthorized"
},
{
code: 406,
responseModel: null,
message: "Not Acceptable"
}
],
method: "get",
nickname: "Users#index"
}
]
}
]
}
```

**Comment by AaronRustad** [comment]
I'm seeing the same thing. @perldork's suggestion corrects the path in the resource file `users.json` but still needs to be fixed for the `api-docs.json` as @xuyao91 suggests.

**Comment by xTrebliG** [comment]
@xuyao91 On line 71 of the generator.rb file i replaced:

**Comment by xTrebliG** [comment]
@xuyao91 On line 71 of the generator.rb file for swagger docs I added a forward slash to the  path

#### From This:
```
resource_api = {
                path: "#{Config.transform_path(trim_leading_slash(debased_path), api_version)}.{format}",
                description: ret[:klass].swagger_config[:description]
              }
```

#### To This:
```
resource_api = {
                path: "/#{Config.transform_path(trim_leading_slash(debased_path), api_version)}.{format}",
                description: ret[:klass].swagger_config[:description]
              }
```

**Comment by xTrebliG** [comment]
adding this to the swagger config file also did the job: 

```
def self.transform_path(path, api_version)
    # Make a distinction between the APIs and API documentation paths.
    "/apidocs/#{path}"
  end
```

**Comment by acidghost** [comment]
@perldork Thanks for the fix! 


@richhollis Does it really cost you so much to keep a gem updated with the contributions from its users...?

**Comment by saurgoel** [comment]
Fixes in my fork.
```
gem 'swagger-docs', git: 'https://github.com/amberteam/swagger-docs'
```

**Comment by scomp** [comment]
+1 grrr

**Comment by richhollis** [comment]
Thanks to all on this thread.

v0.2.0 attempts to address this issue by removing the trailing slash on the base path and by adding it to api paths.
