### ISSUE TITLE
Dropdown create 

### ISSUE THREAD

**Issue by shefalee93** [richhollis/swagger-docs#119]
Hello,

Can you please help me as I am not able to create drop down by using database value as option. 

I have tried using enum , but not worked for me, Please provide me correct syntax.

Thank you.

**Comment by richhollis** [comment]
Example: 

```ruby
param_list :form, "freq", :string, :optional, "Frequency", ["daily", "monthly", "monthly"]
```

**Comment by richhollis** [comment]
And now also:

Support for Enums (PR #108)

property_list :type, :string, :optional, "Type", ["info", "warning", "error"]
