### ISSUE TITLE
Does it work with rails-api? (Clone from #75)

### ISSUE THREAD

**Issue by CQBinh** [richhollis/swagger-docs#122]
Hi, i meet the same issue with issue #75 I have follow his solluton, here is my config:
```
Swagger::Docs::Config.base_api_controller = ActionController::API 
# Sollution from github docs: https://github.com/richhollis/swagger-docs#inheriting-from-a-custom-api-controller
# class Swagger::Docs::Config
#   def self.base_api_controller
#     ActionController::API  
#   end
# end

Swagger::Docs::Config.register_apis({
  "1.0" => {
    :controller_base_path => "",
    :api_file_path => "public"
  }
})
```
And i still get `1.0: 0 processed / 4 skipped` when run rake task.
My controller:
```
class UsersController < ApplicationController
  # include Swagger::Docs::ImpotentMethods
  #   Swagger::Docs::Generator::set_real_methods

  swagger_controller :users, "Users"

  swagger_api :index do
    summary "Fetches all users"
    response :unauthorized
    response :not_acceptable
  end

  def index
    render :json => {result:"Success"}, :status => 200
  end

end
```

**Comment by kattybilly** [comment]
Swagger checks for and scans for controller files in your rails app, hence it even scans -
*ApplicationController, ActionController, AccessController, ... etc* as many controllers might be present and hence marks them as skipped when you run the rake task with command-
$rake swagger:docs

Hence, this i presume is working as expected.

**Comment by CQBinh** [comment]
Thanks, but the main issue that i want to focus is: there is no `Controller` get processed. And I don't know how to fix it :(
Could you tell me?

**Comment by kattybilly** [comment]
Swagger works on a Controller method or an API you are framing up or there must be something wrong with your swagger configs.
I would recommend you to go through the Swagger documentation again of how the Swagger fetches the Controller functions and it's corresponding swagger config.

**Comment by CQBinh** [comment]
Did you config `swagger-docs` for `rails-api` before?

**Comment by kattybilly** [comment]
Yes, i have and currently using as well.

On Thu, Oct 22, 2015 at 9:08 PM, Cao Quang Binh <notifications@github.com>
wrote:

> Did you config swagger-docs for rails-api before?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/richhollis/swagger-docs/issues/122#issuecomment-150265454>
> .
>



-- 
Regards,

Kartik Verma
Google Student Ambassador-Alumni
SE-II,.Amazon Development Centre India Pvt. Ltd
____________________________________

Hand Phone no.:  +91- 7032991136

Website <https://sites.google.com/site/kartx111/> | Google+
<https://plus.google.com/+KartikVerma/posts> | LinkedIn
<http://in.linkedin.com/pub/kartik-verma/52/367/417> | Facebook
<http://www.facebook.com/kattty.v>

**Comment by CQBinh** [comment]
So, could you write a mini demo, so I can compare and figure out what wrong in my code.
I'm really appriciate your help.
Thanks again.

**Comment by richhollis** [comment]
In addition to the obeservations above, swagger-docs was not built to specifically support rails-api.
