### ISSUE TITLE
Is there a way of setting nested params?

### ISSUE THREAD

**Issue by vjdhama** [richhollis/swagger-docs#125]
For a `post` request i have a nested param. Something like this : 

```
{
  "user" : {
    "name": "test",
    "email": "foo@bar.com",
    "phone": "424234234",
    "password": "password",
    "password_confirmation": "password"
  }
}

```

How would I send params in `swagger_api :create`?

**Comment by richhollis** [comment]
This should be supported. See: https://github.com/richhollis/swagger-docs/issues/2
