### ISSUE TITLE
Is it possible to skip some controllers while running the rake task?

### ISSUE THREAD

**Issue by ankitjaggi** [richhollis/swagger-docs#130]
I have 4 APIs, of which 3 need to be clubbed together and 1 needs to be separately documented. So I need 2 different api_docs.json files. Is there a way I could tell the rake task to skip a particular controller?

**Comment by richhollis** [comment]
Sorry, there is no support for that. You might be able to generate the documents and then in a post step process them in some way that allows you to separate them out.

**Comment by toshitapandey** [comment]
@richhollis Is this feature available now?
