### ISSUE TITLE
Query String Parameters not showing

### ISSUE THREAD

**Issue by akhare22sandeep** [richhollis/swagger-docs#135]
I have actions , shortcuts and rest set to false on few controllers and updated routes.js for each method action (custom routes).
Now when i generate the documents its not having any information about the parameters (query Parameters). 
Am i missing something ? why my documentation is missing Parameters section for all custom methods. 

my application is written in sails (node.js)

**Comment by richhollis** [comment]
Hi there. This is gem for rails not sails or node. Maybe you want this project: https://github.com/tjwebb/sails-swagger. Cheers.
