### ISSUE TITLE
Deprecated version of swagger

### ISSUE THREAD

**Issue by glaksmono** [richhollis/swagger-docs#138]
We're getting this:

```javascript
{
	schemaValidationMessages: [{
		level: "error",
		message: "Deprecated Swagger version. Please visit http://swagger.io for information on upgrading to Swagger 2.0"
	}]
}
```

we're using this:

```
gem 'swagger-docs', '0.2.8'
```

any ideas how to fix this?

**Comment by richhollis** [comment]
I guess swagger have possibly added a deprecation warning for older 1.x version schemas. v2 is not supported by this gem. From this project's README:

> This project supports elements of the v1.2 swagger specification. It does not support the v2 specification. If you are looking for support for the newer specification the please see the swagger-blocks project
