### ISSUE TITLE
Multiple params in get request

### ISSUE THREAD

**Issue by techverx** [richhollis/swagger-docs#153]
can we send multiple parameters in get request.
    param :query, :auth_token, :strig, :required, "Auth token"
    param :path, :nested_id, :integer, :required, "Team Id" 
it show two fileds but request only take query parameters, it is not sending nested_id along with request.
i have to send liks auth_token="asss" &id=3 in get request.
Anybody can help?

**Comment by myeung58** [comment]
Seems like you're trying to put both auth_token and id in a query string? Try this:
``` 
param :query, :auth_token, :string, :required, "Auth token"
param :query, :id, :integer, :required, "Team Id"
```

**Comment by techverx** [comment]
thanks
