### ISSUE TITLE
Nested Resources in Rails

### ISSUE THREAD

**Issue by r3trosteve** [richhollis/swagger-docs#39]
Hi, 
I'm trying to figure out how to implement swagger in my rails app. I have it working for top level resources, but for nested resources I can't find a solution.

Let's say I have:

```
resources :products do
    resources :slots
end
```

How do I structure the 

```
swagger_controller :slots, "Slot Management"
```

for building my slots methods based on my slots controller actions?

The documentation just refers to a simple top level resource (users).

Appreciate any advice you can give

thanks

Steve

**Comment by joshS314159** [comment]
Similar issue here.

If I have the follows in my routes:
```
resources :users do
  resources :user_rooms 
end
```
With this path: ```/users/:id/user_rooms.json```

```
resources :organization do
  resources :users do
    resources :user_rooms 
  end
end
```
And with this path: ```/organization/:id/users/:user_id/user_rooms.json```


I only get the first route in my documentation and not the second. Can I explicitly document these two variations of the same endpoints?
