### ISSUE TITLE
Param as an array of swagger_model object?

### ISSUE THREAD

**Issue by rvindas-gap** [richhollis/swagger-docs#71]
Hi, in a Ruby on Rails application, we have a swagger_model called Disk and the following is the parameter I am specifying in the corresponding swagger_api entry:

param :body, :disks, :Disk, :optional, "An array of disks"

How could I make this parameter an array in order to behave like this example: http://petstore.swagger.wordnik.com/#!/user/createUsersWithArrayInput ?

Thanks in advance

**Comment by matt-hu** [comment]
how to set name property under Model Machine an default value?
