### ISSUE TITLE
Please make 'transform_path' part of the configuration

### ISSUE THREAD

**Issue by robotarmy** [richhollis/swagger-docs#86]
We have a 'swagger_docs' discovery url - that we are using transform_path for it works.

We have a 'base_path' for the API that is the actual live api.

The trouble with the config as is - our swagger 'discovery_path' gets conflated with the 'base_path' and then we end up with swagger_ui generating weird paths. 

Transform_path solved our issue - perhaps the config could have a seperate config key for 'swagger_base_path' for the server location of the swagger docs to replace monkeypatching transform_path.

Thank you for your consideration.

**Comment by tagrudev** [comment]
This is relevant I have the same problem

**Comment by richhollis** [comment]
Can you see if this still a problem in the latest version and if it is re-open. Thanks.
