### ISSUE TITLE
Does swagger-docs support OAuth 2.0?

### ISSUE THREAD

**Issue by rhazegh** [richhollis/swagger-docs#97]
Can I generate json spec files that are capable of handling OAuth 2.0 authentication in the swagger-ui?

**Comment by fotinakis** [comment]
Just to steal some thunder and offer an alternative here, this is supported by my [swagger-blocks](https://github.com/fotinakis/swagger-blocks) gem if you're interested (bearing in mind that it's an unrelated project and a different doc format). Example oauth2 code [here](https://github.com/fotinakis/swagger-blocks/blob/980f9b415e0f2980105bc12a72cff7c1170fc883/spec/lib/swagger_blocks_spec.rb#L36).

**Comment by McRip** [comment]
huge +1 for this too!

**Comment by fotinakis** [comment]
This was highly requested in [swagger-blocks](https://github.com/fotinakis/swagger-blocks) too, so I just added docs for how to do it: https://github.com/fotinakis/swagger-blocks#security-handling

**Comment by richhollis** [comment]
I know this issue is old, but thanks to @rhazegh for the PR. I've used all of your code to implement the authorizations support. Thanks so much for that!

**Comment by rhazegh** [comment]
@richhollis the PR was made by @RKushnir
